# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f9ccd84ff2971d23cb4b96fe7e5392c266677c6f27a1b69017c682122ca7c4a203f50ce206e7bfe926bf4aedcb9dfbe65965b93bf8774b127c37fd2d456943e

test:
  secret_key_base: 7c7fa4661484dbfcb5911127ac5566cfa9a5fe53ba089fa22acd634eef0303e77e93c9d2ae4bc9cb98173d069e9ad89967853300814072634d404c756fc24b96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
